AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Venafi-WebSDK-NodeJS

  Sample SAM Template for Venafi-WebSDK-NodeJS
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TPPLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: tpp-lambda/
      Handler: venafi-app.lambdaHandler
      Runtime: nodejs8.10
      Events:
        TPPWeb:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tpp
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TPPLambdaApi:
    Description: "API Gateway endpoint URL for Prod stage for TPP Lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tpp/"
  TPPLambdaFunction:
    Description: "TPP Lambda Function ARN"
    Value: !GetAtt TPPLambdaFunction.Arn
  TPPLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for TPP Lambda function"
    Value: !GetAtt TPPLambdaFunctionRole.Arn
